### ISSUE TITLE
Using universal prefix argument C-u C-u

### ISSUE THREAD

**Issue by 4DA** [PythonNut/flx-isearch#4]
`flex-isearch-mode` sets advice over `isearch-forward` and calls `flex-isearch` when <kbd>C-u</kbd> <kbd>C-u</kbd> is used before isearch.

Can `flx-isearch` employ the same stuff?

**Comment by PythonNut** [comment]
I see no reason why not.

**Comment by PythonNut** [comment]
I'll see if I can work on this over the Weekend.

**Comment by PythonNut** [comment]
Hey, sorry. I've been super busy, and I think I'll be busy for at least another week. I'll get to this as soon as I can.

**Comment by PythonNut** [comment]
Should be working now.
