### ISSUE TITLE
Failing to use flx-search from elisp code.

### ISSUE THREAD

**Issue by hatschipuh** [PythonNut/flx-isearch#6]
Hi, first of all thank you for this awesome package!

I have the following problem:
I would like to call `flx-search-forward` from elisp but I have problems to get it to work. Sometimes it works, but only a few times, and if I switch buffers it stops working, too. It only seems to work after flx-isearch-forward was called interactively in the buffer where I want to use it. Would really appreciate some help how to get this working. I'm not an elisp expert and more of a hobby programmer, so I'm a little bit stuck.

**Comment by PythonNut** [comment]
I'll be looking into this today.

**Comment by PythonNut** [comment]
This is currently blocked by #7.

**Comment by PythonNut** [comment]
@hatschipuh I can't seem to reproduce your problem. Please update, and see if the problem goes away. If it does not, then please give some instructions on how to reproduce it.

**Comment by hatschipuh** [comment]
@PythonNut It still does not work for me. I want to call it from elisp so for example if I'm adding this `(flx-search-forward "fimp")` after the comment section of flx-isearch.el and evaluate the expression I get the message `flx forward search failed`. But I would like to get the result of that search or expect it to jump to that, which would be ` flx-isearch-message-prefix`. `flx-isearch-forward` works but I want to search buffers from elisp and get the results if that is possible. English is not my first language, sorry if I'm express it in a complicated way.

**Comment by PythonNut** [comment]
@hatschipuh okay, I get what you're saying now.

Because `flx-isearch` is stateful, you'll need to call `flx-isearch-initialize-state` before you start searching.  

I use the state to record the current symbol being searched (remember that `flx-isearch` will search all occurrences of the first symbol before cycling to the next.)

**Comment by hatschipuh** [comment]
Ah, thanks. Okay I will play with this a little bit :)
