### ISSUE TITLE
Switch from isearch directly to flx?

### ISSUE THREAD

**Issue by hatschipuh** [PythonNut/flx-isearch#9]
Hi,

I'm trying to use isearch-forward on default and only on demand switch to flx. I would like to take the search string I typed in already and immediately search with flx-isearch from the beginning of the buffer. For now I only got it working with flx-search-forward with the following:

    (defun isearch-to-flx ()
        (interactive)
        (unless (eq last-command this-command)
            (with-isearch-suspended
                (goto-char (point-min))))
        (flx-search-forward isearch-string))

How could this work with flx-isearch-forward?
Any help is greatly appreciated!

**Comment by PythonNut** [comment]
Hi. Thanks for the suggestion! 

Right now, there's some large breakages that need to be fixed once Emacs 25 lands, so I'm going to wait for it to be released before I work on anything new. 

I'll look at it after that, okay?

**Comment by hatschipuh** [comment]
Okay, with help from the flex-isearch code I got it working already. A nice idea I got from that code too is to auto switch if normal search fails. Once the Emacs 25 issue is fixed I could test and provide the code I use, if you are interested. Otherwise you can close this if you want. Thanks!

**Comment by PythonNut** [comment]
Thanks!
